### ISSUE TITLE
Will the future plan consider supporting mobile push interface?

### ISSUE THREAD

**Issue by guzishiwo** [cozy-elixir/alibaba_cloud_kit#1]
url: https://next.api.aliyun.com/api/Push/2016-08-01/Push

**Comment by c4710n** [comment]
I found a line in the doc:
> 本产品（移动推送/2016-08-01）的OpenAPI采用[RPC](https://help.aliyun.com/zh/sdk/product-overview/v3-request-structure-and-signature?spm=a2c4g.2249910.0.0.7f153fddgmHjlO)签名风格，签名细节参见[签名机制说明](https://help.aliyun.com/zh/sdk/product-overview/v3-request-structure-and-signature?spm=a2c4g.2249910.0.0.7f153fddgmHjlO)。

It's using RPC style API, so in theory, it has been supported. You can try:
1. build a raw HTTP request according to <https://help.aliyun.com/document_detail/2249916.html>.
2. sign the HTTP request by using `AlibabaCloudKit.Signature.ACS3`.
3. send the HTTP request.

**Comment by guzishiwo** [comment]
I wonder if this library mainly provides the underlying services of open api, or can it support the interfaces of related services? After knowing this, I can know whether I am involved in contributing the push related code.

**Comment by c4710n** [comment]
This library aims to provide general helper functions to build API calls. Currently, It only provides:

* signature related helper functions.

I do not want it to become a one-stop comprehensive SDK. You can read more about my thoughts at https://github.com/cozy-elixir/proposals/blob/main/ship-utilities-for-building-platform-sdks.md
